### PR TITLE
Scripts: FanControl Json LangControl i18n

### PR DESCRIPTION
**Pull request by Caio99BR**
I think it's necesary to enforce usage of this in the next commits

### CODE REVIEW

**Comment by Rem0o** [comment]
Can we make this run as part of a Github action or something like that?   Thought about it but just haven't found a neat way to integrate this.  I won't just dump the script in there without any type of CI integration.

**Comment by Caio99BR** [comment]
Yes, it's possible

Like this, for exemple, create a automated PR when detected changes:
https://github.com/jy95/pkgi-ps3-nopaystation/blob/main/.github/workflows/NoPayStation_updates_checker.yml
https://github.com/jy95/pkgi-ps3-nopaystation/blob/main/.github/workflows/release.yml

I think the best approach would be enforce on checklist of PR request like this (less work i think):
https://github.com/ps2homebrew/Open-PS2-Loader/commit/6f8cd1a17f5d0382fc6e2a5ac0b7580807abc716

**Comment by Caio99BR** [comment]
The bash script need to be fixed, it's converting to wrong endline

**Comment by Rem0o** [comment]
I used this PR as an inspiration and create my own powershell script with a Github action.  We now have a file standard and every PR will be blocked in the script is not ran.

**Pull request closed without merging**
