### PR TITLE
Update ControlCard.it.json

### PR DESCRIPTION
**Pull request by LandOfDar**

### CODE REVIEW

**Comment by LandOfDar** [comment]
Fixed some grammar and changed some terms to keep the consistency with the rest of the translation.

**Comment by Rem0o** [comment]
Please do not open 1 PR per file.

**Comment by LandOfDar** [comment]
I'm trying to find instructions to do so, but it doesn't make me merge my pulls, it just keeps adding up notifications to make PRs. Maybe I'm just too dumb, I guess the easiest thing for me is deleting my fork or account.

**Comment by LandOfDar** [comment]
I'm sorry for my ignorance about GitHub. I just found a friend of mine that is willing to help me understand better how to handle this stuff, but if you also have any insight for me, I'm listening. Now if it's a huge problem I will proceed to close down the other pull requests and maybe try to merge them all in one to make it convenient for you, cheers!

**Pull request closed without merging**
